trigger:
  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Terraform
    jobs:
      - job: ApplyTFConfig
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: TerraformInstaller@0
            inputs:
              terraformVersion: '0.12.20'
          - task: TerraformTaskV1@0
            inputs:
              command: 'init'
              provider: 'azurerm'
              backendServiceArm: '$(azure_subscription)'
          - task: TerraformTaskV1@0
            inputs:
              command: 'plan'
              provider: 'azurerm'
              environmentServiceNameAzureRM: '$(azure_subscription)'
              commandOptions: >-
                -var a_strong_pw='$(a_strong_pw)'
                -input=false
          - task: TerraformTaskV1@0
            inputs:
              command: 'apply'
              provider: 'azurerm'
              environmentServiceNameAzureRM: '$(azure_subscription)'
              commandOptions: >-
                -var a_strong_pw='$(a_strong_pw)'
                -input=false