trigger:

  batch: true
  branches:
    include:
      - '*'

pr:
  branches:
    include:
      - '*'

stages:
  - stage: Terraform
    jobs:
      - job: Install
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: terraformInstaller@0
            inputs:
              terraformVersion: '0.12.20'
          - task: TerraformTaskV1@0
            inputs:
              backendServiceArm: '$(azure_subscription)'
              workingDirectory: '$(Build.ArtifactStagingDirectory)'
              backendAzureRmResourceGroupName: 'tfstate'
              backendAzureRmStorageAccountName: 'tfstate71ac2932'
              backendAzureRmContainerName: 'tfstate'
              backendAzureRmKey: terraform.tfstate
          - task: TerraformTaskV1@0
            inputs:
              command: plan
              workingDirectory: '$(Build.ArtifactStagingDirectory)'
              environmentServiceNameAzureRM: '$(azure_subscription)'
          