web_server_location         = "westus2"
web_server_rg               = "web-rg"
resource_prefix             = "web-server"
web_server_address_space    = "1.0.0.0/22"
web_server_name             = "web"
environment                 = "x" 
web_server_count            = 2
web_server_subnets          = ["1.0.1.0/24", "1.0.2.0/24"]
terraform_script_version    = "1.00"
domain_name_label           = "learning-tf-web"